add django-specific uuid and decimal scalars
mirumee/ariadne pull request #389
Opened 2020-06-19 02:03 UTC by kedlav

Provides scalars for commonly used django types - UUID and Decimal.  Incorrect decimal parsing can lead to unpleasant data quality issues, so providing an opinionated scalar that follow's django's best practices is advised.

2020-06-26 03:37 UTC, kedlav commented
This should be ready for review

2020-10-07 21:00 UTC, gdalmau requested changes

2020-10-07 21:00 UTC, gdalmau commented on tests/django/test_scalars.py
> +        parse_datetime_value("meow")
Use `parse_uuid_value` instead

2020-11-08 20:40 UTC, gdalmau approved these changes
Fix merge conflicts so the PR can be ready for review :)

2021-04-17 21:12 UTC, maxmorlocke commented
Closing, present in ariadne_django, targeted for release 0.2.0

2021-04-17 21:12 UTC, closed without merging