Handle possible None enum value
mirumee/ariadne pull request #711
Opened 2021-10-27 19:03 UTC by kissgyorgy

`default_value` can be None in `InputValueDefinitionNode` (and any other subclass
of `DefinitionNode.default_value` property), so it should be handled at all times.

Refactored the `enum_values_in_input_type` and `enum_values_in_field_args` to use
the same helper function, so they can consistently handle the same edge case.

2021-11-04 10:43 UTC, rafalp commented
Hi! Can you add tests demonstrating the issue fixed here?

2021-11-08 16:20 UTC, rafalp requested changes

2021-11-08 16:20 UTC, rafalp commented on ariadne/enums.py
> +def _get_field_with_keys(field_name, fields):
We are ordering logic in our code from top to bottom, so this should be declared below `enum_values_in_field_args`.

2021-11-08 21:06 UTC, kissgyorgy commented
> Hi! Can you add tests demonstrating the issue fixed here?

Yes, sorry. I will add a minimal reproduction about the issue.

2021-11-09 20:49 UTC, rafalp commented
I'll tangentially schedule this on next release. Sounds like helpful thing to fix.

2021-11-19 17:29 UTC, rafalp approved these changes

2021-11-19 17:29 UTC, merged