Feature: Basic Federation 2 Support
mirumee/ariadne pull request #861
Opened 2022-05-06 16:28 UTC by lleadbet

As noted in #846, Ariadne currently doesn't support Federation 2, although it is currently possible to shim support by adding in the directive definitions manually. 

Instead of that, this PR allows Federation 2 schemas to be parsed without those additional definitions. Additionally, it supports detection of Federation 2 schemas via use of a regex (https://github.com/mirumee/ariadne/compare/master...lleadbet:master#diff-3d0aaa258a6dfa9e431dc1ff3364b944a62a9ab2a7dc47b621cb01d603695eb0R87) to ensure only the correct definitions are pulled in. 

Once this PR is merged in, I'll work to add it to the `apollo-federation-subgraph-compatibility` repository to denote support, but an updated result shows: 

| Language | Library | Federation 1 Support | Federation 2 Support |
| --- | --- | --- | --- |
| Python | [Ariadne](https://ariadnegraphql.org/docs/apollo-federation) | <table><tr><th>_service</th><td>✅</td></tr><tr><th>@key (single)</th><td>✅</td></tr><tr><th>@key (multi)</th><td>❌</td></tr><tr><th>@key (composite)</th><td>❌</td></tr><tr><th>@requires</th><td>✅</td></tr><tr><th>@provides</th><td>✅</td></tr><tr><th>@ftv1</th><td>❌</td></tr></table> | <table><tr><th>@link</th><td>✅</td></tr><tr><th>@shareable</th><td>✅</td></tr><tr><th>@tag</th><td>✅</td></tr><tr><th>@override</th><td>✅</td></tr><tr><th>@inaccessible</th><td>✅</td></tr></table> |

Which matches with expectations. 

Since new directives don't require additional work by subgraphs, this is a simple passthrough for support.

2022-05-06 18:00 UTC, pigletto commented
@lleadbet just to note, seems you have a bit outdated apollo-federation-subgraph-compatibility. It now has better results for Federation 1 support (I've submitted PR there recently).

2022-05-06 18:12 UTC, lleadbet commented
> @lleadbet just to note, seems you have a bit outdated apollo-federation-subgraph-compatibility. It now has better results for Federation 1 support (I've submitted PR there recently).

Ah! Forgot I was working on a fork for a bit. Re-ran with the updates and edited the PR to show the correct results.

2022-05-11 14:23 UTC, rafalp requested changes

2022-05-11 15:45 UTC, lleadbet commented
> How is this regex going to perform with [large-ish schema](https://github.com/saleor/saleor/blob/main/saleor/graphql/schema.graphql)?

Pulling that in (along with a minor regex optimization) doesn't appear to have a significant additional load. If there's a preferred way to pull that, just let me know.

2022-05-11 16:25 UTC, lleadbet commented
Using a cProfile script on it shows  it's much longer on the parser; it's minimal between searching for it and it not existing.

2022-05-12 10:23 UTC, rafalp approved these changes

2022-05-12 10:24 UTC, merged

2022-05-12 10:24 UTC, rafalp commented
Looks great, thank you!

2022-06-28 16:51 UTC, lleadbet commented
Any update on when this might land?

2022-08-05 18:47 UTC, rafalp commented
This is now available in `0.16.0b1` beta release.