Option to enable convert kwargs to snake case globally
mirumee/ariadne pull request #905
Opened 2022-08-05 16:12 UTC by enwawerueli

A global option for the `convert_kwargs_to_snake_case` decorator would be nice to have. This is especially useful if this is the desired behavior for all resolvers

2022-08-05 18:37 UTC, rafalp commented
Hi! There's better way to enable this behavior than through decorator. Every input field and argument has `out_name` attribute that can be set to custom value. Eg. if you set `out_name` on field `name` to `bob`, `name: "test"` in GraphQL query will be passed to `bob` kwarg/dict key. This is approach that Ariadne GraphQL Modules uses:

- Input fields: https://github.com/mirumee/ariadne-graphql-modules/blob/main/ariadne_graphql_modules/input_type.py#L117
- Fields args: https://github.com/mirumee/ariadne-graphql-modules/blob/main/ariadne_graphql_modules/object_type.py#L123

We could have an utility function that iterates schema types and if those types are `GraphQLInputType` or `GraphQLObjectType` we could set out names on those types. This util would be then called by `make_executable_schema` to do it's magic.

2022-08-07 22:12 UTC, enwawerueli commented
Noted. I haven't tried out graphql-modules, so I'll have a closer look at that first

2022-09-07 12:44 UTC, rafalp requested changes
Looking okay, but could you please add tests?

2022-09-07 12:44 UTC, rafalp commented on ariadne/objects.py
> +
Format code with black.

2022-09-07 12:44 UTC, rafalp commented on ariadne/executable_schema.py
> +    if kwargs_to_snake_case:
I'm curious if this should be an option or just a utility that you can run against your schema separately. But I guess the latter would require us to create a utility that copies whole schema so we don't mutate it.

2022-09-07 12:44 UTC, rafalp commented on ariadne/executable_schema.py
> +    kwargs_to_snake_case: bool = False
How about `convert_args_to_snake_case`?

2022-09-07 12:44 UTC, rafalp commented on ariadne/executable_schema.py
> +            field.out_name = convert_camel_case_to_snake(field_name)
We should do `if isinstance(graphql_type, GraphQLInputObjectType)` and then set field.out_name, then `if isinstance(graphql_type, GraphQLObjectType)` do that for args.

2022-09-07 12:44 UTC, rafalp commented on ariadne/executable_schema.py
> +        if not isinstance(graphql_type, (GraphQLObjectType, GraphQLInputObjectType)):
We should do `if isinstance(graphql_type, GraphQLInputObjectType)` and then set field.out_name, then `if isinstance(graphql_type, GraphQLObjectType)` do that for args.

2022-09-07 12:45 UTC, rafalp commented on ariadne/executable_schema.py
> +def set_outname_to_snake_case(schema) -> None:
```suggestion
def set_outnames_to_snake_cases(schema) -> None:
```

2022-09-08 04:23 UTC, enwawerueli commented
@rafalp I've incorporated the changes you suggested. Should be all good!

2022-09-08 04:33 UTC, enwawerueli commented
Also noted a name like `complexField_Int32` converts to `complex_field__int_32`, not sure if that's the intended behavior or it should be `complex_field_int_32`. Not a problem though

2022-09-08 10:51 UTC, rafalp commented on ariadne/executable_schema.py
> +def set_outnames_to_snake_case(schema) -> None:
```suggestion
def set_out_names_to_snake_case(schema) -> None:
```

2022-09-08 10:51 UTC, rafalp commented on ariadne/executable_schema.py
> +        set_outnames_to_snake_case(schema)
```suggestion
        set_out_names_to_snake_case(schema)
```

2022-09-08 10:52 UTC, rafalp commented
Left some extra notes but those are tiny bits and nothing blocking - but code needs to be formatted with black to pass tests.

2023-01-17 18:51 UTC, rafalp commented
Thank you for contributing this. Can you say if approach from #1007 also works for you?

Thank you!

2023-01-17 18:51 UTC, closed without merging